# This is a basic workflow to help you get started with Actions

name: AKS Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.1.0
        with:
          # Optional SDK version(s) to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x
          dotnet-version: 3.1.x
      - name: dotnet build
        run: dotnet build -c release
        
      - name: docker build
        run: docker build -t githubactions-aks-demo:'{{github.sha}}' .
        
      - name: Docker login
        run: docker login -username '${{secrets.DOCKER_HUB_USERNAME}}' -password '${{secrets.DOCKER_HUB_ACCESS_TOKEN}}'
        
      - name: docker image tag
        run: docker tag githubactions-aks-demo:'${{github.sha}}' '${{secrets.DOCKER_HUB_USERNAME}}'/githubactions-aks-demo:'${{github.sha}}'
        
      - name: docker push
        run: docker push '${{secrets.DOCKER_HUB_USERNAME}}'/githubactions-aks-demo:'${{github.sha}}'
        
        
        
        
        
        
        
        
        
        
